### ISSUE TITLE
Remove the input file immediately

### ISSUE THREAD

**Issue by Kuraky** [TheDeveloperDen/advent-of-code-2023#3]
My lawyer advises me, since Advent of Code's [Legal Notice](https://www.reddit.com/r/adventofcode/wiki/faqs/copyright/inputs/) does not allow for reproduction of inputs, which means, that in the eye of the law, having the input file posted publicly is illegal.
Please fix bug.
![Joe Biden screaming violently at a child while a sharp blue blob is forming between them](https://github.com/TheDeveloperDen/advent-of-code-2023/assets/38810662/b7802c84-f815-4cb4-a8f7-2ced23fd23f0)

**Comment by bristermitten** [comment]
holy shit i did not know this thank u
